# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive/Capstone_FPGA_project/Floating_point_mult/Floating_point_mult.srcs/sources_1/ip/floating_point_mult/floating_point_mult.xci
# IP: The module: 'floating_point_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/Capstone_FPGA_project/Floating_point_mult/Floating_point_mult.gen/sources_1/ip/floating_point_mult/floating_point_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_mult'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/OneDrive/Capstone_FPGA_project/Floating_point_mult/Floating_point_mult.srcs/sources_1/ip/floating_point_mult/floating_point_mult.xci
# IP: The module: 'floating_point_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/Capstone_FPGA_project/Floating_point_mult/Floating_point_mult.gen/sources_1/ip/floating_point_mult/floating_point_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
